- hosts: all
  become: true

  tasks:
    - name: Ensure repository key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ensure docker registry is available
      apt_repository: repo='deb https://download.docker.com/linux/ubuntu jammy stable' state=present

    - name: Ensure docker and dependencies are installed
      apt: name=docker-ce update_cache=yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true