Vagrant.configure(2) do |config|
    config.vm.box_check_update = false
    config.vm.box = "boxen/ubuntu-22.04-x86_64"
    config.vm.define "zytrams" do |s|
        s.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 1
            vb.customize ["modifyvm", :id, "--name", "zytrams", "--natdnsproxy1", "on", "--natdnshostresolver1", "on"]
        end
        
        s.vm.network :private_network, ip: "192.168.42.110"
        s.vm.hostname = "zytrams"  
        s.vm.provision "shell", privileged: true, path: "scripts/pepega.sh"
    end
end